# Generated by Django 5.0.7 on 2024-07-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
